# Generated by Django 4.2.6 on 2023-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano', models.PositiveSmallIntegerField(default='2023')),
                ('cor', models.CharField(max_length=200)),
                ('km_rodados', models.PositiveBigIntegerField(default=0)),
                ('cambio', models.CharField(choices=[('ma', 'Manual'), ('au', 'Automático')], default='ma', max_length=2)),
            ],
        ),
    ]
