# Generated by Django 4.2.6 on 2023-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_carro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='preço',
            field=models.PositiveBigIntegerField(default=40000),
            preserve_default=False,
        ),
    ]
