# Generated by Django 4.2.6 on 2023-10-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_carro_preço'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='preço',
            new_name='preco',
        ),
    ]
