# Generated by Django 4.2.6 on 2023-10-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_rename_preço_carro_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cambio',
            field=models.CharField(choices=[('mn', 'Manual'), ('au', 'Automático')], default='mn', max_length=2),
        ),
    ]
